travis:
  secure:
    BINSTAR_TOKEN: Mvv1DmKxAUoYAAG+KMNEvQy43ecYyQCMyvcx9RE9uqSWZR9wF2nbCN/VJxVj/8w1DP9uYEKMnYBIa/Ag2AJruYCJQm9E8jk4DSDUe4/DDGNXebDlcLNa8xlVcQ/huDuJ8H/2NSn/riKoToCe53apPZXeoP24PIBqiWU0h0Rm4EHF1LVWXWLscspapaBuXqU38uGPz3ARKK98AePkVXiLdx0EgGtHjLfexjFina+NsmpD8q83yNOpDdURgct97/V+RKk0EbQyJc1oTQ9NcNBWSBvaWuLBTLKBYZWq91YkrNeCTbuGeG7CjoNzjd5Wf1YpQLsssUPFEJs9euVWN76cMi1EDxSeUq35EG3FFEQ7ZJ+c8AlcZ6WTdE9JPTtcC+avPGN/suo1plYSvHNDx8vM4iqTAMwasHhMQuiyZHj9hiOl6lYbpSVxwpN7aBHfjjF5CO3gmpkEY1SQeOlFldhiocFeQBsF0uCw799Ae711hUbjTiFB3zhZv90YRR7HQeRxXNVGr4wj3EMnMkC/ocNaUSzDgY/e7ABKV9ZPufuHoD85vxIDlGdixI4uBr7DmI2IO3pxYxWIjoRZrXCTtPpyvoRUIQSa8oyW6cg+5CNXb1pakkICv5m91GaGzyxiEWJYUQ3RAbxfuonm3ih43LZ1Ej2FQWig2ly6ky416gxfa9Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
